# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    btcpayserver
    charge-lnd
    clightning
    electrs
    extra-container
    lightning-pool
    lndconnect
    nbxplorer;

  inherit (pkgsUnstable)
    bitcoind-knots
    clboss
    elementsd
    fulcrum
    lightning-loop
    lnd;

  inherit pkgs pkgsUnstable;
}
