# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable: pkgs-25_05:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    btcpayserver
    charge-lnd
    clightning
    electrs
    elementsd
    extra-container
    lightning-pool
    teos
    teos-watchtower-plugin
    lndconnect;

  inherit (pkgsUnstable)
    bitcoind-knots
    clboss
    fulcrum
    lightning-loop
    lnd;

  inherit pkgs pkgsUnstable pkgs-25_05;
}
